// lib/setAssets.ts
// Maps exact DB set_name values to public asset paths.
// Files live in public/set-assets/{logos,symbols,eras}/
// Returns null for any set without an asset — components handle graceful fallback.

const LOGO_MAP: Record<string, string> = {
  // ── WotC Base era ──────────────────────────────────────────────────────────
  'Base Set':               'Base Set.webp',
  'Base Set 2':             'Base Set 2.webp',
  'Jungle':                 'Jungle.webp',
  'Fossil':                 'Fossil.webp',
  'Team Rocket':            'Team Rocket.webp',
  'Gym Heroes':             'Gym Heroes.webp',
  'Gym Challenge':          'Gym Challenge.webp',
  'Neo Genesis':            'Neo Genesis.webp',
  'Neo Discovery':          'Neo Discovery.webp',
  'Neo Revelation':         'Neo Revelatio.webp',
  'Neo Destiny':            'Neo Destiny.webp',
  'Legendary Collection':   'Legendary Collection.webp',
  'Expedition':             'Expedition.webp',
  'Aquapolis':              'Aquapolis.webp',
  'Skyridge':               'Skyridge.webp',
  // ── EX era ────────────────────────────────────────────────────────────────
  'Ruby & Sapphire':        'Ruby & Sapphire.webp',
  'Sandstorm':              'Sandstorm.webp',
  'Dragon':                 'Dragon.webp',
  'Team Magma & Team Aqua': 'Team Magma vs Team Aqua.webp',
  'Hidden Legends':         'Hidden Legends.webp',
  'Fire Red & Leaf Green':  'FireRed & LeafGreen.webp',
  'Deoxys':                 'Deoxys.webp',
  'Emerald':                'Emerald.webp',
  'Unseen Forces':          'Unseen Forces.webp',
  'Delta Species':          'Delta Species.webp',
  'Legend Maker':           'Legend Maker.webp',
  'Holon Phantoms':         'Holon Phantoms.webp',
  'Crystal Guardians':      'Crystal Guardians.webp',
  'Dragon Frontiers':       'Dragon Frontiers.webp',
  'Power Keepers':          'Power Keepers.webp',
  // ── Diamond & Pearl era ───────────────────────────────────────────────────
  'Diamond & Pearl':        'Diamond & Pearl.webp',
  'Mysterious Treasures':   'Mysterious Treasures.webp',
  'Secret Wonders':         'Secret Wonders.webp',
  'Great Encounters':       'Great Encounters.webp',
  'Majestic Dawn':          'Majestic Dawn.webp',
  'Legends Awakened':       'Legends Awakened.webp',
  'Stormfront':             'Stormfront.webp',
  // ── Platinum era ──────────────────────────────────────────────────────────
  'Platinum':               'Platinum.webp',
  'Rising Rivals':          'Rising Rivals.webp',
  'Supreme Victors':        'Supreme Victors.webp',
  'Arceus':                 'Arceus.webp',
  // ── HeartGold & SoulSilver era ────────────────────────────────────────────
  'HeartGold & SoulSilver': 'HeartGold & SoulSilver.webp',
  'Unleashed':              'Unleashed.webp',
  'Undaunted':              'Undaunted.webp',
  'Triumphant':             'Triumphant.webp',
  'Call of Legends':        'Call of Legends.webp',
  // ── Black & White era ─────────────────────────────────────────────────────
  'Black & White':          'Black & White.webp',
  'Emerging Powers':        'Emerging Powers.webp',
  'Noble Victories':        'Noble Victories.webp',
  'Next Destinies':         'Next Destinies.webp',
  'Dark Explorers':         'Dark Explorer.webp',
  'Dragons Exalted':        'Dragons Exalted.webp',
  'Dragon Vault':           'Dragon Vault.webp',
  'Boundaries Crossed':     'Boundaries Crossed.webp',
  'Plasma Storm':           'Plasma Storm.webp',
  'Plasma Freeze':          'Plasma Freeze.webp',
  'Plasma Blast':           'Plasma Blast.webp',
  'Legendary Treasures':    'Legendary Treasures.webp',
  // ── XY era ────────────────────────────────────────────────────────────────
  'XY':                     'XY.webp',
  'Flashfire':              'Flashfire.webp',
  'Furious Fists':          'Furious Fists.webp',
  'Phantom Forces':         'Phantom Forces.webp',
  'Primal Clash':           'Primal Clash.webp',
  'Double Crisis':          'Double Crisis.webp',
  'Roaring Skies':          'Roaring Skies.webp',
  'Ancient Origins':        'Ancient Origins.webp',
  'BREAKthrough':           'BREAKthrough.webp',
  'BREAKpoint':             'BREAKpoint.webp',
  'Generations':            'Generations.webp',
  'Fates Collide':          'Fates Collide.webp',
  'Steam Siege':            'Steam Siege.webp',
  'Evolutions':             'Evolutions.webp',
  'Mega Evolution':         'Mega Evolution.webp',
  // ── Sun & Moon era ────────────────────────────────────────────────────────
  'Sun & Moon':             'Sun & Moon.webp',
  'Guardians Rising':       'Guardians Rising.webp',
  'Burning Shadows':        'Burning Shadows.webp',
  'Shining Legends':        'Shining Legends.webp',
  'Crimson Invasion':       'Crimson Invasion.webp',
  'Ultra Prism':            'Ultra Prism.webp',
  'Forbidden Light':        'Forbidden Light.webp',
  'Celestial Storm':        'Celestial Storm.webp',
  'Dragon Majesty':         'Dragon Majesty.webp',
  'Lost Thunder':           'Lost Thunder.webp',
  'Team Up':                'Team Up.webp',
  'Detective Pikachu':      'Detective Pikachu.webp',
  'Unbroken Bonds':         'Unbroken Bonds.webp',
  'Unified Minds':          'Unified Minds.webp',
  'Hidden Fates':           'Hidden Fates.webp',
  'Cosmic Eclipse':         'Cosmic Eclipse.webp',
  // ── Sword & Shield era ────────────────────────────────────────────────────
  'Sword & Shield':         'Sword & Shield.webp',
  'Rebel Clash':            'Rebel Clash.webp',
  'Darkness Ablaze':        'Darkness Ablaze.webp',
  "Champion's Path":        "Champion's Path.webp",
  'Vivid Voltage':          'Vivid Voltage.webp',
  'Shining Fates':          'Shining Fates.webp',
  'Battle Styles':          'Battle Styles.webp',
  'Chilling Reign':         'Chilling Reign.webp',
  'Evolving Skies':         'Evolving Skies.webp',
  'Celebrations':           'Celebrations.webp',
  'Fusion Strike':          'Fusion Strike.webp',
  'Brilliant Stars':        'Brilliant Stars.webp',
  'Astral Radiance':        'Astral Radiance.webp',
  'Go':                     'Pokemon Go.webp',
  'Lost Origin':            'Lost Origin.webp',
  'Silver Tempest':         'Silver Tempest.webp',
  'Crown Zenith':           'Crown Zenith.webp',
  // ── Scarlet & Violet era ──────────────────────────────────────────────────
  'Scarlet & Violet':       'Scarlet & Violet.webp',
  'Paldea Evolved':         'Paldea Evolved.webp',
  'Obsidian Flames':        'Obsidian Flames.webp',
  'Scarlet & Violet 151':   '151.webp',
  'Paradox Rift':           'Paradox Rift.webp',
  'Paldean Fates':          'Paldean Fates.webp',
  'Temporal Forces':        'Temporal Forces.webp',
  'Twilight Masquerade':    'Twilight Masquerade.webp',
  'Shrouded Fable':         'Shrouded Fable.webp',
  'Stellar Crown':          'Stellar Crown.webp',
  'Surging Sparks':         'Surging Sparks.webp',
  'Prismatic Evolutions':   'Prismatic Evolutions.webp',
  'Phantasmal Flames':      'Phantasmal Flames.webp',
  'Journey Together':       'Journey Together.webp',
  'Destined Rivals':        'Destined Rivals.webp',
  'Perfect Order':          'Perfect Order.webp',
  // ── Misc / promos ─────────────────────────────────────────────────────────
  'Rumble':                 'Pokemon Rumble.webp',
  'Southern Islands':       'Southern Islands.webp',
  'White Flare':            'White Flare.webp',
  'Black Bolt':             'Black Bolt.webp',
  'Ascended Heroes':        'Ascended Heroes.webp',
  'Trick or Trade 2024':    'Trick or Trade 2024.webp',
  'POP Series 1':           'Pop Series 1.webp',
  'POP Series 2':           'Pop Series 2.webp',
  'POP Series 3':           'Pop Series 3.webp',
  'POP Series 4':           'Pop Series 4.webp',
  'POP Series 5':           'Pop Series 5.webp',
  'POP Series 6':           'Pop Series 6.webp',
  'POP Series 7':           'Pop Series 7.webp',
  'POP Series 8':           'Pop Series 8.webp',
  'POP Series 9':           'Pop Series 9.webp',
}

const SYMBOL_MAP: Record<string, string> = {
  // ── WotC / early ──────────────────────────────────────────────────────────
  'Base Set 2':             'Base Set 2.png',
  'Jungle':                 'Jungle.png',
  'Fossil':                 'Fossil.png',
  'Team Rocket':            'Team Rocket.png',
  'Gym Heroes':             'Gym Heroes.png',
  'Gym Challenge':          'Gym Challenge.png',
  'Neo Genesis':            'Neo Genesis.png',
  'Neo Discovery':          'Neo Discovery.png',
  'Neo Revelation':         'Neo Revelation.png',
  'Neo Destiny':            'Neo Destiny.png',
  'Legendary Collection':   'Legendary Collection.png',
  'Expedition':             'Expedition.png',
  'Aquapolis':              'Aquapolis.png',
  'Skyridge':               'Skyridge.png',
  // ── EX era ────────────────────────────────────────────────────────────────
  'Ruby & Sapphire':        'Ruby and Sapphire.png',
  'Sandstorm':              'Sandstorm.png',
  'Dragon':                 'Dragon.png',
  'Team Magma & Team Aqua': 'Team Magma vs Team Aqua.png',
  'Hidden Legends':         'Hidden Legends.png',
  'Fire Red & Leaf Green':  'Fire Red and Leaf Green.png',
  'Deoxys':                 'Deoxys.png',
  'Emerald':                'Emerald.png',
  'Unseen Forces':          'Unseen Forces.png',
  'Delta Species':          'Delta Species.png',
  'Legend Maker':           'Legend Maker.png',
  'Holon Phantoms':         'Holon Phantoms.png',
  'Crystal Guardians':      'Crystal Guardians.png',
  'Dragon Frontiers':       'Dragon Frontiers.png',
  'Power Keepers':          'Power Keepers.png',
  // ── DP era ────────────────────────────────────────────────────────────────
  'Diamond & Pearl':        'Diamond & Pearl.png',
  'Mysterious Treasures':   'Mysterious Treasures.png',
  'Secret Wonders':         'Secret Wonders.png',
  'Great Encounters':       'Great Encounters.png',
  'Majestic Dawn':          'Majestic Dawn.png',
  'Legends Awakened':       'Legends Awakened.png',
  'Stormfront':             'Stormfront.png',
  // ── Platinum era ──────────────────────────────────────────────────────────
  'Platinum':               'Platinum.png',
  'Rising Rivals':          'Rising Rivals.png',
  'Supreme Victors':        'Supreme Victors.png',
  'Arceus':                 'Arceus.png',
  // ── HGSS era ──────────────────────────────────────────────────────────────
  'HeartGold & SoulSilver': 'HeartGold and SoulSilver.png',
  'Unleashed':              'Unleashed.png',
  'Undaunted':              'Undaunted.png',
  'Triumphant':             'Triumphant.png',
  'Call of Legends':        'Call of Legends.png',
  // ── BW era ────────────────────────────────────────────────────────────────
  'Black & White':          'Black and White.png',
  'Emerging Powers':        'Emerging Powers.png',
  'Noble Victories':        'Noble Victories.png',
  'Next Destinies':         'Next Destinies.png',
  'Dark Explorers':         'Dark Explorers.png',
  'Dragons Exalted':        'Dragons Exalted.png',
  'Dragon Vault':           'Dragon Vault.png',
  'Boundaries Crossed':     'Boundaries Crossed.png',
  'Plasma Storm':           'Plasma Storm.png',
  'Plasma Freeze':          'Plasma Freeze.png',
  'Plasma Blast':           'Plasma Blast.png',
  'Legendary Treasures':    'Legendary Treasures.png',
  // ── XY era ────────────────────────────────────────────────────────────────
  'XY':                     'XY.png',
  'Flashfire':              'Flashfire.png',
  'Furious Fists':          'Furious Fists.png',
  'Phantom Forces':         'Phantom Forces.png',
  'Primal Clash':           'Primal Clash.png',
  'Double Crisis':          'Double Crisis.png',
  'Roaring Skies':          'Roaring Skies.png',
  'Ancient Origins':        'Ancient Origins.png',
  'BREAKthrough':           'BREAKthrough.png',
  'BREAKpoint':             'BREAKpoint.png',
  'Generations':            'Generations.png',
  'Fates Collide':          'Fates Collide.png',
  'Steam Siege':            'Steam Siege.png',
  'Evolutions':             'Evolutions.png',
  'Mega Evolution':         'Mega Evolution.png',
  // ── SM era ────────────────────────────────────────────────────────────────
  'Sun & Moon':             'Sun & Moon.png',
  'Guardians Rising':       'Guardians Rising.png',
  'Burning Shadows':        'Burning Shadows.png',
  'Shining Legends':        'Shining Legends.png',
  'Crimson Invasion':       'Crimson Invasion.png',
  'Ultra Prism':            'Ultra Prism.png',
  'Forbidden Light':        'Forbidden Light.png',
  'Celestial Storm':        'Celestial Storm.png',
  'Dragon Majesty':         'Dragon Majesty.png',
  'Lost Thunder':           'Lost Thunder.png',
  'Team Up':                'Team Up.png',
  'Detective Pikachu':      'Detective Pikachu.png',
  'Unbroken Bonds':         'Unbroken Bonds.png',
  'Unified Minds':          'Unified Minds.png',
  'Hidden Fates':           'Hidden Fates.png',
  'Cosmic Eclipse':         'Cosmic Eclipse.png',
  // ── SWSH era ──────────────────────────────────────────────────────────────
  'Sword & Shield':         'Sword & Shield.png',
  'Rebel Clash':            'Rebel Clash.png',
  'Darkness Ablaze':        'Darkness Ablaze.png',
  "Champion's Path":        "Champion's Path.png",
  'Vivid Voltage':          'Vivid Voltage.png',
  'Shining Fates':          'Shining Fates.png',
  'Battle Styles':          'Battle Styles.png',
  'Chilling Reign':         'Chilling Reign.png',
  'Evolving Skies':         'Evolving Skies.png',
  'Celebrations':           'Celebrations.png',
  'Fusion Strike':          'Fusion Strike.png',
  'Brilliant Stars':        'Brilliant Stars.png',
  'Astral Radiance':        'Astral Radiance.png',
  'Go':                     'Pokemon Go.png',
  'Lost Origin':            'Lost Origin.png',
  'Silver Tempest':         'Silver Tempest.png',
  'Crown Zenith':           'Crown Zenith.png',
  // ── SV era ────────────────────────────────────────────────────────────────
  'Scarlet & Violet':       'Scarlet & Violet.png',
  'Paldea Evolved':         'Paldea Evolved.png',
  'Obsidian Flames':        'Obsidian Flames.png',
  'Scarlet & Violet 151':   '151.png',
  'Paradox Rift':           'Paradox Rift.png',
  'Paldean Fates':          'Paldean Fates.png',
  'Temporal Forces':        'Temporal Forces.png',
  'Twilight Masquerade':    'Twilight Masquerade.png',
  'Shrouded Fable':         'Shrouded Fable.png',
  'Stellar Crown':          'Stellar Crown.png',
  'Surging Sparks':         'Surging Sparks.png',
  'Prismatic Evolutions':   'Prismatic Evolutions.png',
  'Phantasmal Flames':      'Phantasmal Flames.png',
  'Journey Together':       'Journey Together.png',
  'Destined Rivals':        'Destined Rivals.png',
  'Perfect Order':          'Perfect Order.png',
  // ── Misc ──────────────────────────────────────────────────────────────────
  'Southern Islands':       'Southern Islands.png',
  'Pikachu Libre & Suicune':'Pikachu Libre & Suicune.png',
  'Promo':                  'Promo.png',
  'Black Bolt':             'Black Bolt.png',
  'White Flare':            'White Flare.png',
  'POP Series 1':           'POP Series 1.png',
  'POP Series 2':           'POP Series 2.png',
  'POP Series 3':           'POP Series 3.png',
  'POP Series 4':           'POP Series 4.png',
  'POP Series 5':           'POP Series 5.png',
  'POP Series 6':           'POP Series 6.png',
  'POP Series 7':           'POP Series 7.png',
  'POP Series 8':           'POP Series 8.png',
  'POP Series 9':           'POP Series 9.png',
  'McDonalds 2016':         "McDonald's 2016.png",
  'McDonalds 2018':         "McDonald's 2018.png",
  'McDonalds 2019':         "McDonald's 2019.png",
  'McDonalds 2021':         "McDonald's 2021.png",
  'McDonalds 2022':         "McDonald's 2022.png",
}

const ERA_MAP: Record<string, string> = {
  'Base Set': 'Base', 'Base Set 2': 'Base', 'Jungle': 'Base', 'Fossil': 'Base', 'Team Rocket': 'Base',
  'Gym Heroes': 'Gym', 'Gym Challenge': 'Gym',
  'Neo Genesis': 'Neo', 'Neo Discovery': 'Neo', 'Neo Revelation': 'Neo', 'Neo Destiny': 'Neo',
  'Legendary Collection': 'Legendary Collection',
  'Expedition': 'e-Card', 'Aquapolis': 'e-Card', 'Skyridge': 'e-Card',
  'Ruby & Sapphire': 'EX Ruby & Sapphire', 'Sandstorm': 'EX Ruby & Sapphire',
  'Dragon': 'EX Ruby & Sapphire', 'Team Magma & Team Aqua': 'EX Ruby & Sapphire',
  'Hidden Legends': 'EX Ruby & Sapphire', 'Fire Red & Leaf Green': 'EX Ruby & Sapphire',
  'Deoxys': 'EX Ruby & Sapphire', 'Emerald': 'EX Ruby & Sapphire',
  'Unseen Forces': 'EX Ruby & Sapphire', 'Delta Species': 'EX Ruby & Sapphire',
  'Legend Maker': 'EX Ruby & Sapphire', 'Holon Phantoms': 'EX Ruby & Sapphire',
  'Crystal Guardians': 'EX Ruby & Sapphire', 'Dragon Frontiers': 'EX Ruby & Sapphire',
  'Power Keepers': 'EX Ruby & Sapphire',
  'Diamond & Pearl': 'Diamond & Pearl', 'Mysterious Treasures': 'Diamond & Pearl',
  'Secret Wonders': 'Diamond & Pearl', 'Great Encounters': 'Diamond & Pearl',
  'Majestic Dawn': 'Diamond & Pearl', 'Legends Awakened': 'Diamond & Pearl', 'Stormfront': 'Diamond & Pearl',
  'Platinum': 'Platinum', 'Rising Rivals': 'Platinum', 'Supreme Victors': 'Platinum', 'Arceus': 'Platinum',
  'HeartGold & SoulSilver': 'HeartGold SoulSilver', 'Unleashed': 'HeartGold SoulSilver',
  'Undaunted': 'HeartGold SoulSilver', 'Triumphant': 'HeartGold SoulSilver',
  'Call of Legends': 'Call of Legends',
  'Black & White': 'Black & White', 'Emerging Powers': 'Black & White',
  'Noble Victories': 'Black & White', 'Next Destinies': 'Black & White',
  'Dark Explorers': 'Black & White', 'Dragons Exalted': 'Black & White',
  'Dragon Vault': 'Black & White', 'Boundaries Crossed': 'Black & White',
  'Plasma Storm': 'Black & White', 'Plasma Freeze': 'Black & White',
  'Plasma Blast': 'Black & White', 'Legendary Treasures': 'Black & White',
  'XY': 'XY', 'Flashfire': 'XY', 'Furious Fists': 'XY', 'Phantom Forces': 'XY',
  'Primal Clash': 'XY', 'Double Crisis': 'XY', 'Roaring Skies': 'XY',
  'Ancient Origins': 'XY', 'BREAKthrough': 'XY', 'BREAKpoint': 'XY',
  'Generations': 'XY', 'Fates Collide': 'XY', 'Steam Siege': 'XY', 'Evolutions': 'XY',
  'Mega Evolution': 'Mega Evolution',
  'Sun & Moon': 'Sun & Moon', 'Guardians Rising': 'Sun & Moon', 'Burning Shadows': 'Sun & Moon',
  'Shining Legends': 'Sun & Moon', 'Crimson Invasion': 'Sun & Moon', 'Ultra Prism': 'Sun & Moon',
  'Forbidden Light': 'Sun & Moon', 'Celestial Storm': 'Sun & Moon', 'Dragon Majesty': 'Sun & Moon',
  'Lost Thunder': 'Sun & Moon', 'Team Up': 'Sun & Moon', 'Detective Pikachu': 'Sun & Moon',
  'Unbroken Bonds': 'Sun & Moon', 'Unified Minds': 'Sun & Moon',
  'Hidden Fates': 'Sun & Moon', 'Cosmic Eclipse': 'Sun & Moon',
  'Sword & Shield': 'Sword & Shield', 'Rebel Clash': 'Sword & Shield',
  'Darkness Ablaze': 'Sword & Shield', "Champion's Path": 'Sword & Shield',
  'Vivid Voltage': 'Sword & Shield', 'Shining Fates': 'Sword & Shield',
  'Battle Styles': 'Sword & Shield', 'Chilling Reign': 'Sword & Shield',
  'Evolving Skies': 'Sword & Shield', 'Celebrations': 'Sword & Shield',
  'Fusion Strike': 'Sword & Shield', 'Brilliant Stars': 'Sword & Shield',
  'Astral Radiance': 'Sword & Shield', 'Go': 'Sword & Shield',
  'Lost Origin': 'Sword & Shield', 'Silver Tempest': 'Sword & Shield', 'Crown Zenith': 'Sword & Shield',
  'Scarlet & Violet': 'Scarlet & Violet', 'Paldea Evolved': 'Scarlet & Violet',
  'Obsidian Flames': 'Scarlet & Violet', 'Scarlet & Violet 151': 'Scarlet & Violet',
  'Paradox Rift': 'Scarlet & Violet', 'Paldean Fates': 'Scarlet & Violet',
  'Temporal Forces': 'Scarlet & Violet', 'Twilight Masquerade': 'Scarlet & Violet',
  'Shrouded Fable': 'Scarlet & Violet', 'Stellar Crown': 'Scarlet & Violet',
  'Surging Sparks': 'Scarlet & Violet', 'Prismatic Evolutions': 'Scarlet & Violet',
  'Phantasmal Flames': 'Scarlet & Violet', 'Journey Together': 'Scarlet & Violet',
  'Destined Rivals': 'Scarlet & Violet', 'Perfect Order': 'Scarlet & Violet',
  'Ascended Heroes': 'Scarlet & Violet',
}

export const ERA_DISPLAY_NAMES: Record<string, string> = {
  'Base': 'Base Era',
  'Gym': 'Gym Era',
  'Neo': 'Neo Era',
  'e-Card': 'e-Card Era',
  'Legendary Collection': 'Legendary Collection',
  'EX Ruby & Sapphire': 'EX Era',
  'Diamond & Pearl': 'Diamond & Pearl Era',
  'Platinum': 'Platinum Era',
  'HeartGold SoulSilver': 'HeartGold & SoulSilver Era',
  'Call of Legends': 'Call of Legends',
  'Black & White': 'Black & White Era',
  'XY': 'XY Era',
  'Mega Evolution': 'Mega Evolution',
  'Sun & Moon': 'Sun & Moon Era',
  'Sword & Shield': 'Sword & Shield Era',
  'Scarlet & Violet': 'Scarlet & Violet Era',
}

export interface SetAssets {
  logoUrl: string | null
  symbolUrl: string | null
  eraUrl: string | null
  eraName: string | null
  eraDisplay: string | null
}

export function getSetAssets(setName: string): SetAssets {
  const logoFile   = LOGO_MAP[setName]   ?? null
  const symbolFile = SYMBOL_MAP[setName] ?? null
  const eraKey     = ERA_MAP[setName]    ?? null

  return {
    logoUrl:    logoFile   ? `/set-assets/logos/${logoFile}`    : null,
    symbolUrl:  symbolFile ? `/set-assets/symbols/${symbolFile}` : null,
    eraUrl:     eraKey     ? `/set-assets/eras/${eraKey}.webp`   : null,
    eraName:    eraKey,
    eraDisplay: eraKey ? (ERA_DISPLAY_NAMES[eraKey] ?? eraKey) : null,
  }
}
