-- Scan quota tracking. Free tier: 100 scans per calendar month per
-- identifier. The identifier is the logged-in user_id when available,
-- otherwise the anonymous device_id (a localStorage UUID generated by
-- the browser). Either is fine — both count as one identity for quota.
--
-- Counting from scan_logs directly so we have a single source of truth.
-- Storing both fields nullable; one of them should always be present.

ALTER TABLE scan_logs ADD COLUMN IF NOT EXISTS user_id   UUID;
ALTER TABLE scan_logs ADD COLUMN IF NOT EXISTS device_id TEXT;

-- Partial indexes — only index rows that have the identifier, since most
-- rows will have exactly one of the two. Keeps the index small.
CREATE INDEX IF NOT EXISTS idx_scan_logs_user_month
  ON scan_logs (user_id, created_at DESC) WHERE user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_scan_logs_device_month
  ON scan_logs (device_id, created_at DESC) WHERE device_id IS NOT NULL;

-- Convenience view: current-month scan counts per identifier. Useful for
-- debugging and for the front-end "X / 100 remaining" display via RPC.
CREATE OR REPLACE VIEW scan_quota_current_month AS
SELECT
  COALESCE('user:' || user_id::text, 'device:' || device_id) AS identifier,
  COUNT(*)::int                                              AS scans_used,
  date_trunc('month', NOW())::date                           AS period_start
FROM scan_logs
WHERE created_at >= date_trunc('month', NOW())
  AND (user_id IS NOT NULL OR device_id IS NOT NULL)
GROUP BY 1;

-- RPC the client can call to ask "how many do I have left?" without
-- needing direct read access to scan_logs (which contains other users'
-- data).
DROP FUNCTION IF EXISTS scan_quota_remaining(uuid, text);
CREATE OR REPLACE FUNCTION scan_quota_remaining(
  p_user_id   uuid DEFAULT NULL,
  p_device_id text DEFAULT NULL
)
RETURNS TABLE (
  scans_used      integer,
  scans_remaining integer,
  monthly_limit   integer
)
LANGUAGE sql
STABLE
AS $$
  WITH used AS (
    SELECT COUNT(*)::int AS n
    FROM scan_logs
    WHERE created_at >= date_trunc('month', NOW())
      AND (
        (p_user_id   IS NOT NULL AND user_id   = p_user_id)
        OR (p_device_id IS NOT NULL AND device_id = p_device_id)
      )
  )
  SELECT
    used.n                              AS scans_used,
    GREATEST(0, 100 - used.n)::int      AS scans_remaining,
    100::int                            AS monthly_limit
  FROM used;
$$;

GRANT EXECUTE ON FUNCTION scan_quota_remaining(uuid, text) TO anon;
GRANT EXECUTE ON FUNCTION scan_quota_remaining(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION scan_quota_remaining(uuid, text) TO service_role;
