-- migrations/2026-06-23-recent-sales-internal-slug-index.sql
-- Block 4B-W-6A — index the card-page hot path on recent_sales.
--
-- WHY THIS IS NEEDED
--   The card-page query (src/lib/recentSales/cardQueries.ts) filters
--   recent_sales by:
--       internal_card_slug = $slug
--       parse_status       = 'ok'
--       review_status      = 'active'
--   ordered by sale_date DESC, limit 100.
--
--   The 2026-06-17 stage-1 migration created two hot-path indexes:
--     * idx_recent_sales_card_section_date   on (card_slug, observed_section, sale_date DESC)
--                                            WHERE parse_status='ok' AND review_status='active'
--                                            AND card_slug IS NOT NULL
--     * idx_recent_sales_provider_section_date on (provider, provider_card_id, observed_section, sale_date DESC)
--                                            WHERE parse_status='ok' AND review_status='active'
--
--   Neither index matches the card-page query:
--     * The leading column is wrong (card_slug / provider_card_id, not
--       internal_card_slug).
--     * As of today every ok+active row has card_slug IS NULL (the
--       scraper writes internal_card_slug but the bridge to cards.card_slug
--       is not populated). The card_slug index therefore covers
--       ZERO rows; it cannot accelerate any read until the bridge is
--       resolved by a future block.
--
--   With ~22.8k ok+active rows across ~1.0k distinct internal_card_slugs
--   today and growth incoming from the scraper, every card-page render
--   currently triggers a sequential heap scan.
--
-- WHAT THIS DOES
--   Adds ONE partial b-tree index keyed on the card-page predicate:
--
--       idx_recent_sales_internal_slug_date
--         ON recent_sales(internal_card_slug, sale_date DESC)
--         WHERE parse_status='ok' AND review_status='active'
--
--   This is the minimum index that turns the card-page query into a
--   bounded index-only-ish lookup: locate the slug in the leading
--   column, walk forward in DESC date order until limit. No filter pass
--   afterwards is required because both equality predicates are baked
--   into the partial predicate.
--
-- NOT CHANGED
--   * No data writes.
--   * No DROP / ALTER / TRUNCATE on existing recent_sales objects.
--   * Pre-existing indexes are KEPT as designed — idx_recent_sales_card_section_date
--     will become useful in a future block once provider_card_links
--     resolution backfills card_slug; removing it now would only need
--     to be re-created later.
--   * provider_sale_key already has a UNIQUE constraint (and therefore
--     an automatic unique b-tree); the scraper's upsert path is
--     already optimal.
--
-- HOW TO APPLY
--   CREATE INDEX CONCURRENTLY cannot run inside a transaction block.
--   The Supabase SQL Editor runs statements outside an explicit BEGIN
--   by default, so the CONCURRENTLY form below is safe to paste in.
--   Do NOT wrap this file in BEGIN/COMMIT. If your migration runner
--   forces a transaction wrapper, use the non-concurrent variant in
--   the section labelled "FALLBACK".
--
-- IDEMPOTENT
--   IF NOT EXISTS makes a re-run a no-op. If a prior partial
--   CONCURRENTLY build was interrupted, the resulting INVALID index
--   must be dropped manually before re-running — see
--   "RECOVERY FROM INTERRUPTED BUILD" at the bottom.

-- ─────────────────────────────────────────────────────────────────────
-- PRIMARY: concurrent partial b-tree index for the card-page hot path
-- ─────────────────────────────────────────────────────────────────────
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_recent_sales_internal_slug_date
  ON public.recent_sales (internal_card_slug, sale_date DESC)
  WHERE parse_status = 'ok' AND review_status = 'active';


-- ─────────────────────────────────────────────────────────────────────
-- FALLBACK: only run this if your runner cannot use CONCURRENTLY.
-- It takes a brief ShareLock on the table (typically <1s at current
-- row counts) — fine when the scraper is idle, painful when it is
-- actively inserting. The CONCURRENTLY variant above is strongly
-- preferred.
-- ─────────────────────────────────────────────────────────────────────
-- CREATE INDEX IF NOT EXISTS idx_recent_sales_internal_slug_date
--   ON public.recent_sales (internal_card_slug, sale_date DESC)
--   WHERE parse_status = 'ok' AND review_status = 'active';


-- ─────────────────────────────────────────────────────────────────────
-- VERIFICATION: paste these queries after the build completes.
-- ─────────────────────────────────────────────────────────────────────
-- 1. List recent_sales indexes with size + uniqueness + definition.
--
-- SELECT
--   c.relname                                  AS index_name,
--   pg_size_pretty(pg_relation_size(c.oid))    AS index_size,
--   ix.indisunique                             AS is_unique,
--   pg_get_indexdef(c.oid)                     AS definition
-- FROM   pg_index ix
-- JOIN   pg_class c   ON c.oid = ix.indexrelid
-- JOIN   pg_class t   ON t.oid = ix.indrelid
-- JOIN   pg_namespace n ON n.oid = t.relnamespace
-- WHERE  n.nspname = 'public'
--   AND  t.relname  = 'recent_sales'
-- ORDER  BY c.relname;
--
-- 2. Confirm planner will use the new index for the card-page query.
--    Replace the slug with any value present in your data.
--
-- EXPLAIN (ANALYZE, BUFFERS)
-- SELECT sale_date, marketplace_source, marketplace_country, observed_section,
--        raw_or_graded, grading_company, grade, condition_bucket, condition_text,
--        best_offer_status, sale_price_cents
-- FROM   public.recent_sales
-- WHERE  internal_card_slug = '11816213'
--   AND  parse_status  = 'ok'
--   AND  review_status = 'active'
-- ORDER  BY sale_date DESC
-- LIMIT  100;
--
--   Expected plan:
--     Limit
--       -> Index Scan using idx_recent_sales_internal_slug_date on recent_sales
--          Index Cond: (internal_card_slug = '...')
--
--   If you instead see "Seq Scan" or "Bitmap Heap Scan + Recheck", the
--   index either has not finished building (status pg_index.indisready)
--   or has been marked INVALID — see recovery section below.


-- ─────────────────────────────────────────────────────────────────────
-- RECOVERY FROM INTERRUPTED BUILD
-- ─────────────────────────────────────────────────────────────────────
-- If a previous CONCURRENTLY build was cancelled mid-flight,
-- pg_index.indisvalid will be FALSE on idx_recent_sales_internal_slug_date.
-- Drop and rebuild:
--
-- DROP INDEX CONCURRENTLY IF EXISTS public.idx_recent_sales_internal_slug_date;
-- CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_recent_sales_internal_slug_date
--   ON public.recent_sales (internal_card_slug, sale_date DESC)
--   WHERE parse_status = 'ok' AND review_status = 'active';
