-- ============================================================================
-- Block 4B-W-2A — Recent-Sales Pilot Allow-List (58-card technical pilot)
-- ============================================================================
--
-- Seeds public.recent_sales_card_allow_list with the 58 cards selected by
-- scripts/select-recent-sales-pilot.sql (committed manifest at
-- data/recent-sales-pilot-100.json — file path kept stable; the *file's*
-- _meta.intended_count is 58).
--
-- The 58-card target is a TECHNICAL PILOT: its goal is to prove scraper
-- wiring, parser execution, Supabase writes, dedup, sparse + sealed
-- handling, and import-run accounting — not statistical completeness.
--
-- IDEMPOTENT: Re-applying this migration does not duplicate rows and does
-- not delete existing allow-list rows. Safe to run twice.
--
-- WHAT IT DOES:
--   * INSERT ... ON CONFLICT DO UPDATE on (provider, provider_card_id)
--   * Sets enabled = true and refreshes the reason string
--   * Runs a DO $$ post-condition block that:
--       - asserts every row maps to provider_card_links with confidence ≥ 0.900
--       - asserts no duplicate provider_card_id was inserted
--       - asserts exactly 58 enabled PriceCharting pilot rows are present
--         (rows with reason LIKE 'pilot:%')
--
-- WHAT IT DOES NOT DO:
--   * Does NOT touch public.recent_sales (no sale rows are inserted)
--   * Does NOT touch public.market_import_runs (no runs are inserted)
--   * Does NOT enable RECENT_SALES_FULL_CATALOGUE (ingestion still gated)
--   * Does NOT enable ingestion (the env flag stays unset/false)
--   * Does NOT alter RLS or any existing pre-Block-4B-W-1 table
--
-- IDs BELOW ARE REAL (2026-06-22 selector run, 58 mapped PriceCharting cards).
-- The DO $$ post-condition still fail-closes if any id is unmapped,
-- low-confidence, or duplicated — the only way this migration applies cleanly
-- is if every id below is currently active in provider_card_links with
-- confidence >= 0.900.
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- Seed inserts (idempotent on (provider, provider_card_id)).
-- Each row's reason starts with 'pilot:<category>' so the post-condition
-- query can scope its count to pilot rows specifically.
-- ----------------------------------------------------------------------------
INSERT INTO public.recent_sales_card_allow_list (provider, provider_card_id, enabled, reason)
VALUES
  -- BEGIN PILOT_ENTRIES (regenerated by scripts/regenerate-pilot-migration.mjs)
  ('pricecharting','12054014',TRUE,'pilot:sealed - is_sealed=true; sealed-product layout coverage'),
  ('pricecharting','6377915',TRUE,'pilot:sealed - is_sealed=true; sealed-product layout coverage'),
  ('pricecharting','9359963',TRUE,'pilot:sealed - is_sealed=true; sealed-product layout coverage'),
  ('pricecharting','11812143',TRUE,'pilot:sealed - is_sealed=true; sealed-product layout coverage'),
  ('pricecharting','7598946',TRUE,'pilot:sealed - is_sealed=true; sealed-product layout coverage'),
  ('pricecharting','11370280',TRUE,'pilot:sealed - is_sealed=true; sealed-product layout coverage'),
  ('pricecharting','4476579',TRUE,'pilot:sealed - is_sealed=true; sealed-product layout coverage'),
  ('pricecharting','7879936',TRUE,'pilot:sealed - is_sealed=true; sealed-product layout coverage'),
  ('pricecharting','9607635',TRUE,'pilot:sealed - is_sealed=true; sealed-product layout coverage'),
  ('pricecharting','9607865',TRUE,'pilot:sealed - is_sealed=true; sealed-product layout coverage'),
  ('pricecharting','11859876',TRUE,'pilot:sparse - few/no recent sales expected; validates no-section behaviour'),
  ('pricecharting','5427869',TRUE,'pilot:sparse - few/no recent sales expected; validates no-section behaviour'),
  ('pricecharting','10034554',TRUE,'pilot:sparse - few/no recent sales expected; validates no-section behaviour'),
  ('pricecharting','10604857',TRUE,'pilot:sparse - few/no recent sales expected; validates no-section behaviour'),
  ('pricecharting','4644675',TRUE,'pilot:sparse - few/no recent sales expected; validates no-section behaviour'),
  ('pricecharting','7273960',TRUE,'pilot:sparse - few/no recent sales expected; validates no-section behaviour'),
  ('pricecharting','10024588',TRUE,'pilot:sparse - few/no recent sales expected; validates no-section behaviour'),
  ('pricecharting','12031804',TRUE,'pilot:sparse - few/no recent sales expected; validates no-section behaviour'),
  ('pricecharting','6736454',TRUE,'pilot:sparse - few/no recent sales expected; validates no-section behaviour'),
  ('pricecharting','8427846',TRUE,'pilot:sparse - few/no recent sales expected; validates no-section behaviour'),
  ('pricecharting','1450205',TRUE,'pilot:difficult_variants - 1st edition / shadowless / reverse holo / promo / stamped / alt art'),
  ('pricecharting','5610835',TRUE,'pilot:difficult_variants - 1st edition / shadowless / reverse holo / promo / stamped / alt art'),
  ('pricecharting','9863989',TRUE,'pilot:difficult_variants - 1st edition / shadowless / reverse holo / promo / stamped / alt art'),
  ('pricecharting','11860014',TRUE,'pilot:difficult_variants - 1st edition / shadowless / reverse holo / promo / stamped / alt art'),
  ('pricecharting','10057828',TRUE,'pilot:difficult_variants - 1st edition / shadowless / reverse holo / promo / stamped / alt art'),
  ('pricecharting','10057829',TRUE,'pilot:difficult_variants - 1st edition / shadowless / reverse holo / promo / stamped / alt art'),
  ('pricecharting','10057830',TRUE,'pilot:difficult_variants - 1st edition / shadowless / reverse holo / promo / stamped / alt art'),
  ('pricecharting','10057831',TRUE,'pilot:difficult_variants - 1st edition / shadowless / reverse holo / promo / stamped / alt art'),
  ('pricecharting','2173311',TRUE,'pilot:difficult_variants - 1st edition / shadowless / reverse holo / promo / stamped / alt art'),
  ('pricecharting','9536051',TRUE,'pilot:vintage_or_wotc - WOTC / e-Card era English set; condition-heavy raw + graded'),
  ('pricecharting','10809812',TRUE,'pilot:vintage_or_wotc - WOTC / e-Card era English set; condition-heavy raw + graded'),
  ('pricecharting','762190',TRUE,'pilot:vintage_or_wotc - WOTC / e-Card era English set; condition-heavy raw + graded'),
  ('pricecharting','762257',TRUE,'pilot:vintage_or_wotc - WOTC / e-Card era English set; condition-heavy raw + graded'),
  ('pricecharting','762286',TRUE,'pilot:vintage_or_wotc - WOTC / e-Card era English set; condition-heavy raw + graded'),
  ('pricecharting','10809811',TRUE,'pilot:vintage_or_wotc - WOTC / e-Card era English set; condition-heavy raw + graded'),
  ('pricecharting','10807012',TRUE,'pilot:vintage_or_wotc - WOTC / e-Card era English set; condition-heavy raw + graded'),
  ('pricecharting','11026995',TRUE,'pilot:vintage_or_wotc - WOTC / e-Card era English set; condition-heavy raw + graded'),
  ('pricecharting','2294039',TRUE,'pilot:vintage_or_wotc - WOTC / e-Card era English set; condition-heavy raw + graded'),
  ('pricecharting','2294041',TRUE,'pilot:vintage_or_wotc - WOTC / e-Card era English set; condition-heavy raw + graded'),
  ('pricecharting','10031879',TRUE,'pilot:psa_or_grade_spread - raw + PSA9 and/or PSA10 active; grade-spread analysis'),
  ('pricecharting','11870545',TRUE,'pilot:psa_or_grade_spread - raw + PSA9 and/or PSA10 active; grade-spread analysis'),
  ('pricecharting','11870547',TRUE,'pilot:psa_or_grade_spread - raw + PSA9 and/or PSA10 active; grade-spread analysis'),
  ('pricecharting','11870536',TRUE,'pilot:psa_or_grade_spread - raw + PSA9 and/or PSA10 active; grade-spread analysis'),
  ('pricecharting','11870543',TRUE,'pilot:psa_or_grade_spread - raw + PSA9 and/or PSA10 active; grade-spread analysis'),
  ('pricecharting','5421501',TRUE,'pilot:psa_or_grade_spread - raw + PSA9 and/or PSA10 active; grade-spread analysis'),
  ('pricecharting','8740493',TRUE,'pilot:modern_or_recent - SwSh / Scarlet & Violet era; active price or sales signal'),
  ('pricecharting','10021255',TRUE,'pilot:general_quality - quality top-up — best available eligible by score'),
  ('pricecharting','10259763',TRUE,'pilot:general_quality - quality top-up — best available eligible by score'),
  ('pricecharting','3725947',TRUE,'pilot:general_quality - quality top-up — best available eligible by score'),
  ('pricecharting','7286177',TRUE,'pilot:general_quality - quality top-up — best available eligible by score'),
  ('pricecharting','10052353',TRUE,'pilot:general_quality - quality top-up — best available eligible by score'),
  ('pricecharting','10053473',TRUE,'pilot:general_quality - quality top-up — best available eligible by score'),
  ('pricecharting','4602699',TRUE,'pilot:general_quality - quality top-up — best available eligible by score'),
  ('pricecharting','4895091',TRUE,'pilot:general_quality - quality top-up — best available eligible by score'),
  ('pricecharting','4928299',TRUE,'pilot:general_quality - quality top-up — best available eligible by score'),
  ('pricecharting','3725878',TRUE,'pilot:general_quality - quality top-up — best available eligible by score'),
  ('pricecharting','3975631',TRUE,'pilot:general_quality - quality top-up — best available eligible by score'),
  ('pricecharting','7286175',TRUE,'pilot:general_quality - quality top-up — best available eligible by score')
  -- END PILOT_ENTRIES
ON CONFLICT (provider, provider_card_id) DO UPDATE
  SET enabled = TRUE,
      reason  = EXCLUDED.reason;

-- ----------------------------------------------------------------------------
-- Post-condition: hard-fail if anything is off.
-- ----------------------------------------------------------------------------
DO $$
DECLARE
  v_pilot_count        INT;
  v_unmapped_count     INT;
  v_low_conf_count     INT;
  v_dup_count          INT;
  v_recent_sales_count INT;
  v_runs_count         INT;
BEGIN
  -- (1) Must be exactly 58 enabled pilot rows (technical pilot target).
  SELECT COUNT(*) INTO v_pilot_count
  FROM public.recent_sales_card_allow_list
  WHERE provider = 'pricecharting'
    AND enabled  = TRUE
    AND reason  LIKE 'pilot:%';
  IF v_pilot_count <> 58 THEN
    RAISE EXCEPTION 'Block 4B-W-2A pilot count = %, expected 58', v_pilot_count;
  END IF;

  -- (2) Every pilot id must map to a valid provider_card_links row.
  SELECT COUNT(*) INTO v_unmapped_count
  FROM public.recent_sales_card_allow_list a
  LEFT JOIN public.provider_card_links l
    ON  l.provider         = a.provider
    AND l.provider_card_id = a.provider_card_id
    AND l.is_active        = TRUE
  WHERE a.provider = 'pricecharting'
    AND a.enabled  = TRUE
    AND a.reason  LIKE 'pilot:%'
    AND (l.provider_card_id IS NULL OR l.card_slug IS NULL);
  IF v_unmapped_count <> 0 THEN
    RAISE EXCEPTION 'Block 4B-W-2A: % pilot rows have no active provider_card_links mapping', v_unmapped_count;
  END IF;

  -- (3) Every linked confidence must be >= 0.900.
  SELECT COUNT(*) INTO v_low_conf_count
  FROM public.recent_sales_card_allow_list a
  JOIN public.provider_card_links l
    ON  l.provider         = a.provider
    AND l.provider_card_id = a.provider_card_id
    AND l.is_active        = TRUE
  WHERE a.provider = 'pricecharting'
    AND a.enabled  = TRUE
    AND a.reason  LIKE 'pilot:%'
    AND l.confidence < 0.900;
  IF v_low_conf_count <> 0 THEN
    RAISE EXCEPTION 'Block 4B-W-2A: % pilot rows have confidence < 0.900', v_low_conf_count;
  END IF;

  -- (4) No duplicate provider_card_id within the pilot.
  SELECT COUNT(*) INTO v_dup_count FROM (
    SELECT provider_card_id
    FROM public.recent_sales_card_allow_list
    WHERE provider = 'pricecharting'
      AND enabled  = TRUE
      AND reason  LIKE 'pilot:%'
    GROUP BY provider_card_id
    HAVING COUNT(*) > 1
  ) d;
  IF v_dup_count <> 0 THEN
    RAISE EXCEPTION 'Block 4B-W-2A: % duplicate provider_card_id values in pilot', v_dup_count;
  END IF;

  -- (5) recent_sales and market_import_runs must remain empty (Stage-1 invariant).
  SELECT COUNT(*) INTO v_recent_sales_count FROM public.recent_sales;
  IF v_recent_sales_count <> 0 THEN
    RAISE EXCEPTION 'Block 4B-W-2A: recent_sales is non-empty (% rows) — pilot must not write sales', v_recent_sales_count;
  END IF;

  SELECT COUNT(*) INTO v_runs_count FROM public.market_import_runs;
  IF v_runs_count <> 0 THEN
    RAISE EXCEPTION 'Block 4B-W-2A: market_import_runs is non-empty (% rows) — pilot must not insert runs', v_runs_count;
  END IF;

  RAISE NOTICE 'Block 4B-W-2A pilot seed OK: 58 enabled rows, all mapped, all confidence >= 0.900';
END$$;

COMMIT;

-- ============================================================================
-- Post-application sanity (operator runs scripts/verify-recent-sales-pilot.sql)
-- Expected: total_enabled_pilot_rows=58, invalid_mappings=0, duplicate_ids=0,
--           low_confidence_rows=0, recent_sales_rows=0, market_import_runs_rows=0.
-- ============================================================================
